version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.docker-compose
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=chinelos_store
      - DB_USER=chinelos_user
      - DB_PASSWORD=${DB_PASSWORD:-chinelos_password_change_this}
    depends_on:
      - db
    volumes:
      - uploads:/app/public/uploads
    networks:
      - chinelos_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=chinelos_store
      - MYSQL_USER=chinelos_user
      - MYSQL_PASSWORD=${DB_PASSWORD:-chinelos_password_change_this}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password_change_this}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chinelos_network

volumes:
  mysql_data:
  uploads:

networks:
  chinelos_network:
    driver: bridge
