version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chinelos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Use external database
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: mysql://tropical:805ce7692e5b4d6ced5f@5.161.52.206:3232/tropical

      # Legacy format (fallback)
      DB_HOST: 5.161.52.206
      DB_PORT: 3232
      DB_USER: tropical
      DB_PASSWORD: 805ce7692e5b4d6ced5f
      DB_NAME: tropical
      MYSQL_HOST: 5.161.52.206
      MYSQL_PORT: 3232
      MYSQL_USER: tropical
      MYSQL_PASSWORD: 805ce7692e5b4d6ced5f
      MYSQL_DATABASE: tropical
    volumes:
      - upload_data:/app/public/uploads
    networks:
      - chinelos-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  upload_data:

networks:
  chinelos-network:
    driver: bridge
