version: "3.8"

services:
  chinelos-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chinelos-store
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      PORT: 80
      DATABASE_URL: "mysql://tropical:805ce7692e5b4d6ced5f@5.161.52.206:3232/tropical"
      JWT_SECRET: "tropical-brasil-secret-key-2025"
      CORS_ORIGIN: "http://localhost"
    volumes:
      - "./public/uploads:/app/public/uploads"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
