version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chinelos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-chinelos_user}
      DB_PASSWORD: ${DB_PASSWORD:?Database password is required}
      DB_NAME: ${DB_NAME:-chinelos_store}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${DB_USER:-chinelos_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:?Database password is required}
      MYSQL_DATABASE: ${DB_NAME:-chinelos_store}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - upload_data:/app/public/uploads
    networks:
      - chinelos-network

  db:
    image: mysql:8.0
    container_name: chinelos-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?Database root password is required}
      MYSQL_DATABASE: ${DB_NAME:-chinelos_store}
      MYSQL_USER: ${DB_USER:-chinelos_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:?Database password is required}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chinelos-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
  upload_data:

networks:
  chinelos-network:
    driver: bridge
