[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]
aptPkgs = ["python3", "python3-pip", "build-essential"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "echo 'Building client...'",
  "npm run build:client",
  "echo 'Building server...'",
  "npm run build:server"
]

[phases.start]
cmd = "npm start"

[staticAssets]
"dist/spa" = "/"
