# Simplified Nixpacks Configuration - Development Mode
[variables]
NODE_ENV = "development"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm install --legacy-peer-deps"
]

[start]
cmd = "npm run dev"
