[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci --only=production", "npm ci"]

[phases.build]
cmds = [
  "rm -rf dist",
  "mkdir -p dist",
  "npm run build"
]

[phases.start]
cmd = "npm start"
