[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"

[staticAssets]
"dist/spa" = "/"
